# Assignment 13 — LSTM Fundamentals

## Part A — Create Dataset

- Create : X shape = (60, 8, 12)

- Classes : 0 or 1

In [2]:
import torch
import torch.nn as nn

X=torch.rand([50,5,10],dtype=torch.float32)
y=torch.randint(0,2,(50,))

print(X)
print(y)
print(X.shape)
print(y.shape)

tensor([[[0.1628, 0.8036, 0.5787,  ..., 0.9538, 0.9257, 0.5143],
         [0.9805, 0.2911, 0.5774,  ..., 0.2226, 0.4861, 0.5689],
         [0.0534, 0.7140, 0.3224,  ..., 0.1883, 0.3419, 0.0537],
         [0.0190, 0.7781, 0.1482,  ..., 0.7451, 0.8951, 0.8482],
         [0.3017, 0.3562, 0.2748,  ..., 0.7239, 0.8114, 0.6094]],

        [[0.1595, 0.7967, 0.5993,  ..., 0.0930, 0.6329, 0.0211],
         [0.1812, 0.4135, 0.7363,  ..., 0.1145, 0.0117, 0.0021],
         [0.0340, 0.2809, 0.8693,  ..., 0.4081, 0.8434, 0.4201],
         [0.9798, 0.0581, 0.3816,  ..., 0.6430, 0.2528, 0.8447],
         [0.2551, 0.8446, 0.8758,  ..., 0.6676, 0.3397, 0.6304]],

        [[0.2300, 0.0088, 0.8906,  ..., 0.1100, 0.6793, 0.2444],
         [0.4223, 0.5482, 0.1031,  ..., 0.4412, 0.7091, 0.4614],
         [0.6016, 0.0959, 0.3573,  ..., 0.3139, 0.3828, 0.1916],
         [0.6298, 0.2680, 0.8155,  ..., 0.5237, 0.9311, 0.8138],
         [0.6054, 0.8980, 0.8863,  ..., 0.4176, 0.4779, 0.6137]],

        ...,

     

## Part B — Build RNN Model

Architecture:

- LSTM -> input_size=10, hidden_size=16, batch_first=True

- Linear(16,2)

In [3]:
class RNN_Model(nn.Module):

    def __init__(self):
        super().__init__()

        self.rnn=nn.RNN(
            input_size=10,
            hidden_size=16,
            batch_first=True
        )
        self.linear=nn.Linear(16,2)

    def forward(self,X):

        output,hidden=self.rnn(X)
        output=output[:, -1, :]
        output = self.linear(output)

        return output
    
model=RNN_Model()


## Part C — Print Shapes

Inside forward print:

- RNN output shape
- Last timestep shape

In [4]:
class RNN_Model_Print_Shapes(nn.Module):

    def __init__(self):
        super().__init__()

        self.rnn=nn.RNN(
            input_size=10,
            hidden_size=16,
            batch_first=True
        )
        self.linear=nn.Linear(16,2)


    def forward(self,X):

        output,hidden=self.rnn(X)
        print("RNN Output Shape:",output.shape)

        output=output[:,-1,:]
        print("Last Timestep Shape:",output.shape)
     
        output=self.linear(output)

        return output
    
print_shape=RNN_Model_Print_Shapes()
print_shape(X)

RNN Output Shape: torch.Size([50, 5, 16])
Last Timestep Shape: torch.Size([50, 16])


tensor([[-0.2776, -0.0602],
        [-0.2658, -0.1900],
        [-0.2736, -0.1452],
        [-0.2316, -0.0590],
        [-0.3261, -0.1947],
        [-0.3020, -0.0864],
        [-0.2656, -0.0893],
        [-0.3224, -0.1670],
        [-0.1735, -0.1008],
        [-0.3056, -0.0974],
        [-0.2296, -0.2447],
        [-0.3586, -0.0582],
        [-0.1914, -0.2090],
        [-0.2576, -0.1580],
        [-0.3178,  0.0011],
        [-0.2435, -0.2131],
        [-0.1978, -0.0269],
        [-0.2553, -0.2083],
        [-0.3575, -0.1607],
        [-0.2655, -0.0536],
        [-0.2573,  0.0333],
        [-0.0824, -0.0288],
        [-0.3118, -0.1481],
        [-0.2408, -0.1738],
        [-0.1873, -0.1127],
        [-0.1868,  0.0529],
        [-0.1672,  0.1452],
        [-0.2849, -0.1062],
        [-0.2206, -0.1890],
        [-0.2527, -0.1330],
        [-0.2478, -0.1580],
        [-0.2378, -0.2120],
        [-0.3939, -0.0476],
        [-0.2800,  0.0382],
        [-0.3203, -0.1344],
        [-0.1493, -0

## Part D — Train

Use:

- CrossEntropyLoss
- Adam

Train:

- 150 epochs

In [5]:
import torch.optim as optim

loss_fn=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=0.01)


for epoch in range(200):
    predictions=model(X)
    loss=loss_fn(predictions,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch%20==0:
        print(f"Epoch: {epoch} Train Loss :, {loss.item()}")


Epoch: 0 Train Loss :, 0.7137097120285034
Epoch: 20 Train Loss :, 0.4755477011203766
Epoch: 40 Train Loss :, 0.07331570982933044
Epoch: 60 Train Loss :, 0.00577250262722373
Epoch: 80 Train Loss :, 0.0015701849479228258
Epoch: 100 Train Loss :, 0.0009027791093103588
Epoch: 120 Train Loss :, 0.0006615228485316038
Epoch: 140 Train Loss :, 0.0005223706248216331
Epoch: 160 Train Loss :, 0.00042717589531093836
Epoch: 180 Train Loss :, 0.00035744530032388866


## Part E — Predictions

- Get predicted classes using:argmax

In [6]:

with torch.no_grad():
    logits=model(X)
    preds=torch.argmax(logits, dim=1)
print(preds)

tensor([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 0])
