# Assignment 2

# Part A — Reshape and Flatten

Create a tensor containing numbers from 1 to 24.

Shape it into: (2, 3, 4)

Then:

- Print original tensor
- Print shape
- Flatten it into a 1D tensor
- Reshape flattened tensor into shape: (4, 6)

In [6]:
import torch

# Create tensor from 1 to 24
x=torch.arange(1,25)

# Reshaping into (2,3,4)
y=x.reshape(2,3,4)
print(y)
print(y.shape)

#Flattening into 1D Tensor
z=y.reshape(-1)
print(z)

#Reshape into (4,6)
m=z.reshape(4,6)
print(m)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
torch.Size([2, 3, 4])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])


## Part B — Indexing and Slicing

Using the (2,3,4) tensor:

 1. Print first block
 2. Print second row of first block
 3. Print last column from all rows and all blocks
 4. Print only even numbers
- Do NOT use loops for even numbers.

In [7]:
# (2,3,4) tensor
print(y)

# First Block
print(y[0])

#Second Row of first block
print(y[0,1])

# Last column form all rows and all blocks
print(y[:,:,-1])

# Print only even numbers
print(y[y%2==0])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([5, 6, 7, 8])
tensor([[ 4,  8, 12],
        [16, 20, 24]])
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])


## Part C — Broadcasting

Create:

- A shape -> (3,4)
- B shape -> (4,)

Perform broadcasting addition:

- A + B

Then explain:

- why broadcasting worked
- how PyTorch matched dimensions

In [8]:
# Create two tensors A and B of shape (3,4) and (4,)
a=torch.rand(3,4)
b=torch.rand(4,)
print(a,b)

# Perform A+B
add = a+b
print(add)
print(add.shape)

tensor([[0.2205, 0.2198, 0.8155, 0.3407],
        [0.6525, 0.9797, 0.6155, 0.1098],
        [0.4984, 0.8391, 0.3550, 0.3877]]) tensor([0.0016, 0.5453, 0.4080, 0.4405])
tensor([[0.2221, 0.7651, 1.2235, 0.7812],
        [0.6541, 1.5250, 1.0235, 0.5502],
        [0.5000, 1.3844, 0.7631, 0.8282]])
torch.Size([3, 4])


### Explanation

For Broadcating , PyTorch compares dimensions.
Two dimensions are compatible if:

- they are equal
- OR one of them is 1

Here:

- A = (3,4)
- B = (4,)

PyTorch aligns from the right side:

- (3,4)
- (  4)

So it interprets B as:

- (1,4)

Now compare:

- 4 == 4 ✔
- 1 can expand to 3 ✔

Final output:

- (3,4)

## Part D — Mini Challenge

Create a random tensor of shape: (5,5)

Replace ALL values less than 0.5 with 0.

Do this WITHOUT loops.

In [9]:
# Creating a random tensor of shape(5,5)
x=torch.rand(5,5)
print(x)

# Replacing values less than 0.5 with 0
x[x<0.5]=0
print(x)

tensor([[0.0526, 0.1693, 0.5537, 0.5605, 0.2390],
        [0.9321, 0.1670, 0.7603, 0.6440, 0.4067],
        [0.9736, 0.1608, 0.4961, 0.1970, 0.1316],
        [0.8762, 0.4647, 0.0702, 0.2481, 0.1691],
        [0.5093, 0.9361, 0.5393, 0.7992, 0.0937]])
tensor([[0.0000, 0.0000, 0.5537, 0.5605, 0.0000],
        [0.9321, 0.0000, 0.7603, 0.6440, 0.0000],
        [0.9736, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8762, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5093, 0.9361, 0.5393, 0.7992, 0.0000]])
